export function exportText(recommendation) {
    if (!recommendation) return '';
    const lines = [];
    lines.push('OPENCLAW STACK RECOMMENDATION');
    lines.push(`Generated on ${new Date().toLocaleDateString()}`);
    lines.push('='.repeat(40));
    lines.push('');

    if (recommendation.environment) {
        const env = recommendation.environment;
        lines.push('ENVIRONMENT');
        lines.push(`  Type: ${env.label}`);
        lines.push(`  Est. Cost: ${env.estCost}`);
        if (env.provider) {
            lines.push(`  Provider: ${env.provider.label}`);
            lines.push(`  Provider Cost: ${env.provider.estCost}`);
        }
        lines.push('');
    }

    if (recommendation.llm) {
        const llm = recommendation.llm;
        lines.push('LLM PROVIDER');
        lines.push(`  Type: ${llm.type}`);
        lines.push(`  Provider: ${llm.provider}`);
        lines.push(`  Est. Cost: ${llm.estCost}`);
        lines.push('');
    }

    if (recommendation.voiceTranscription) {
        const v = recommendation.voiceTranscription;
        const stub = v.status === 'phase2_stub' ? ' [PHASE 2]' : '';
        lines.push(`VOICE TRANSCRIPTION${stub}`);
        lines.push(`  Provider: ${v.provider}`);
        lines.push(`  Est. Cost: ${v.estCost}`);
        lines.push('');
    }

    if (recommendation.tts) {
        const t = recommendation.tts;
        const stub = t.status === 'phase2_stub' ? ' [PHASE 2]' : '';
        lines.push(`TEXT-TO-SPEECH${stub}`);
        lines.push(`  Provider: ${t.provider}`);
        lines.push(`  Est. Cost: ${t.estCost}`);
        lines.push('');
    }

    if (recommendation.security) {
        const sec = recommendation.security;
        lines.push('SECURITY POSTURE');
        lines.push(`  Posture: ${sec.posture}`);
        lines.push(`  Recommendation: ${sec.recommendation}`);
        lines.push('');
    }

    if (recommendation.hardware) {
        const hw = recommendation.hardware;
        lines.push(`HARDWARE (${hw.label})`);
        lines.push(`  Minimum: ${hw.minimum.ram}, ${hw.minimum.cpu}`);
        lines.push(`  Recommended: ${hw.recommended.description}`);
        lines.push(`  Est. Cost: ${hw.estCost}`);
        if (hw.suggestVps) lines.push('  NOTE: Consider a VPS alternative.');
        lines.push('');
    }

    lines.push('-'.repeat(40));
    // lines.push('Generated by OpenClaw Stack Wizard');
    return lines.join('\n');
}
